### ISSUE TITLE
No "Connect to device" Option

### ISSUE THREAD

**Issue by steve5031** [ghostiam/BrokenEye#5]
I installed the app and the opening screen shows up but there is no "Connect to device" menu item. I have attached the screen I see and the screen from you install instructions file. 

My startup sequence is to start up my Crystal and have it ready. I then launch the BrokenEye app but no Connect to device option. 

Thanks for your help,

Cheers,
Steve

[How To Use Screen.pdf](https://github.com/ghostiam/BrokenEye/files/14070140/How.To.Use.Screen.pdf)
[Broken Eye Config Screen.pdf](https://github.com/ghostiam/BrokenEye/files/14070141/Broken.Eye.Config.Screen.pdf)

**Comment by ghostiam** [comment]
Hello, check that you have the Pimax Play client running and Eye Tracking enabled in the settings, because judging by the screenshot, BrokenEye does not see the device.

![PimaxEyeTrackingEnableSettings](https://github.com/ghostiam/BrokenEye/assets/12181586/830ebe1b-d960-457e-bb68-739c822d6dff)
https://support.pimax.com/en/support/solutions/articles/60000986033-crystal-eye-tracking-troubleshooting-steps

If you launch BrokenEye before connecting the headset, you must manually refresh the list of devices by clicking on the icon to the right of the device selection.

![BrokenEyeRefreshDevicesList](https://github.com/ghostiam/BrokenEye/assets/12181586/4cd9f025-44aa-4bbd-ad4e-188f5a5d7b06)
