### ISSUE TITLE
Eye tracking randomly stops working

### ISSUE THREAD

**Issue by cadergator10** [ghostiam/BrokenEye#9]
Hello. So sometimes the eye tracking just stops working, like after 45 or so minutes it loses connection to the headset, only remediable by closing and reopening brokeneye.

**Comment by ghostiam** [comment]
Hello. This occurs due to loss of USB packets in the cable. The cable or USB hub may be damaged.

At the moment, due to problems with my headset and pending support from Pimax, the project is suspended. As soon as the problem is resolved, I will upload a new version with a fix that may help solve this problem with disconnections.

**Comment by cadergator10** [comment]
ah I see, thank you.
